Use native types where possible + ctor prop promotion
engelsystem/engelsystem pull request #1045
Opened 2022-12-15 19:13 UTC by weeman1337

- Native prop types
- Native return types
- Native param types
- Ctor prop promotion

Also contains a new `.git-blame-ignore-revs` that can be used to ignore this changes for `git blame`.

[pipeline](https://chaos.expert/engelsystem/engelsystem/-/pipelines/36937)

2022-12-17 14:12 UTC, ximex commented
I'm not a fan of the new syntax where you could remove the class property definitions if they got directly defined in the constructor.
what is with all the `// phpcs:ignore`? why not set the type?

2022-12-17 15:16 UTC, weeman1337 commented
> I'm not a fan of the new syntax where you could remove the class property definitions if they got directly defined in the constructor. 

Oh you mean it is great to have to write all the boilerplate

```php
private string $something;

public function __construct(string $somthing)
{
    $this->something = $something;
}
```

instead of just

```php
public function __construct(private string $something) {}
```

:wink: 

> what is with all the `// phpcs:ignore`? why not set the type?

Params that are not typed in the base classes of a lib (yet).

2022-12-17 15:45 UTC, ximex commented
i know it's much boilerplate code. i also like it if there is a way with less typing. In this case i like it more to have all properties (except that one from parent classes) in one place to see what is there. just my 2 cent

2022-12-20 10:25 UTC, MyIgel requested changes

2022-12-20 10:25 UTC, MyIgel commented on src/Controllers/Admin/NewsController.php
>          $this->redirect = $redirector;
Also here (and following)

2022-12-20 12:51 UTC, MyIgel requested changes

2022-12-20 12:51 UTC, MyIgel commented on src/Helpers/Schedule/Conference.php
>          $this->acronym = $acronym;
Thats the same but why not replaced?

2022-12-20 12:51 UTC, MyIgel commented on src/Helpers/Schedule/XmlParser.php
>       * @return array
Is also redundant

2022-12-20 20:09 UTC, weeman1337 commented on src/Controllers/NewsController.php
>       * @param array $data
Commented on old commit

2022-12-21 11:46 UTC, merged