hide input time icon for chrome based browsers
engelsystem/engelsystem pull request #1060
Opened 2022-12-29 15:18 UTC by ximex

before:
![image](https://user-images.githubusercontent.com/1078640/209973379-fe6ce439-c93c-4918-b3da-66aca3f6c71d.png)
after:
![image](https://user-images.githubusercontent.com/1078640/209973294-130782aa-4e07-427b-9a06-213fae101458.png)

should we also hide the date-picker icon?
```css
input[type='time']::-webkit-calendar-picker-indicator,
input[type='datetime-local']::-webkit-calendar-picker-indicator {
  display: none;
  -webkit-appearance: none;
}
```

2023-01-02 17:58 UTC, weeman1337 commented
Thanks for the screenshots :+1: 

Isn't the time picker icon not was chrome-based browser users expect to see? @MyIgel any opinion on that?

2023-01-02 18:57 UTC, ximex commented
the problem is also that there is a bug that it's not possible to change the icon color

2023-01-03 09:54 UTC, weeman1337 commented
Need to do some research on that…

2023-01-03 14:40 UTC, MyIgel commented
For the sake of a consistent look i would also prevent hiding the chrome icon so that it can be styled independently.

2023-01-03 19:14 UTC, weeman1337 requested changes
If we remove the icon, we loose the time picker function of the browser.

It is possible to invert the icon for dark modes:

![image](https://user-images.githubusercontent.com/6216686/210425380-90be2b92-16af-46ab-84bd-78342ee26da8.png)

```
input[type='time']::-webkit-calendar-picker-indicator {
     filter: invert(1);
}
```

We should then use [this icon](https://icons.getbootstrap.com/icons/arrow-counterclockwise/) for the „reset to now“ button.

What do you think? Can you apply these changes?

2023-01-03 19:59 UTC, ximex commented
`invert(1)` is a bit to much white. maybe `0.5`?

2023-01-04 07:45 UTC, weeman1337 commented
It should have the same colour as the button. I would suggest adding this to the dark style file and also use a variable with the option for a default value for it. Then we can tweak it for specific themes, if required.

2023-01-22 20:37 UTC, MyIgel requested changes

2023-01-22 20:37 UTC, MyIgel commented on resources/assets/themes/dark.scss
> +/* Hide the clock icon for Chrome */
It does not hide it but inverts it.
Also the reset button should be changed as weeman mentioned.

2023-01-22 22:54 UTC, ximex commented
which reset button do you mean? the "now" button?

2023-01-22 23:11 UTC, MyIgel commented
@ximex yes that one -> when having two identical icons its confusing esp. when they do different  things.

2023-01-22 23:58 UTC, ximex commented
done

2023-01-24 18:45 UTC, merged