Confirmation popup for deletion
engelsystem/engelsystem pull request #1247
Opened 2023-11-05 01:09 UTC by MyIgel

This PR creates confirmation popups before deleting some entities from their overview pages.

![Screenshot_20231105_020628](https://github.com/engelsystem/engelsystem/assets/1448057/64760e98-8902-4ab2-906d-caa4ed83eafe)

2023-11-05 10:12 UTC, xuwhite commented
> This PR creates confirmation popups before deleting some entities from their overview pages.
> 
> ![Screenshot_20231105_020628](https://user-images.githubusercontent.com/1448057/280500352-64760e98-8902-4ab2-906d-caa4ed83eafe.png)

I think it would look better if you aline the two buttons

2023-11-05 10:28 UTC, xuwhite requested changes

2023-11-05 10:28 UTC, xuwhite commented on resources/views/pages/news/news.twig
> +                                {{ f.delete(null, {'size': 'sm', 'confirm_title': comment.text[:40]|e}) }}
Ive tried it and in news it doesnt work for me at the moment

2023-11-05 10:28 UTC, xuwhite commented on resources/views/pages/questions/overview.twig
> +                                                    {{ f.delete(null, {'size': 'sm', 'confirm_title': question.text[:40]|e}) }}
it would be nice if it would show which type I am deleting (here Question ...)

2023-11-05 10:28 UTC, xuwhite commented on resources/views/admin/rooms/index.twig
> +                                                {{ f.delete(null, {'size': 'sm','confirm_title': room.name|e}) }}
it would be nice if it would show which type I am deleting (here Location ...)

2023-11-05 10:28 UTC, xuwhite commented on resources/views/admin/rooms/index.twig
> +                                                {{ f.delete(null, {'size': 'sm','confirm_title': room.name|e}) }}
the popup should also pop up if xout try to delete it in the edit view

2023-11-05 10:28 UTC, xuwhite commented on resources/views/pages/questions/overview.twig
> +                                                    {{ f.delete(null, {'size': 'sm', 'confirm_title': question.text[:40]|e}) }}
the popup should also pop up if xout try to delete it in the edit view

2023-11-05 10:30 UTC, xuwhite commented
the delete worklog page should also be a popup for consistency

2023-11-05 10:39 UTC, xuwhite commented
instead of the trashcan i would like "delete" better

2023-11-06 23:03 UTC, MyIgel commented
Only remaining task here could be to show what type of something gets deleted but i don't think that would be that useful as you normally know that "Saal 1" is a room, "Angel" an angeltype and "Please get your shirts while they are hot" a news

2023-11-10 07:56 UTC, xuwhite commented
> Only remaining task here could be to show what type of something gets deleted but i don't think that would be that useful as you normally know that "Saal 1" is a room, "Angel" an angeltype and "Please get your shirts while they are hot" a news

It's not always that clear and I think it would improve usability and make more clear what impact the deletion could have

2023-11-13 17:06 UTC, weeman1337 approved these changes
Looks good :beers:  tested and works :rocket:

2023-11-13 17:28 UTC, merged