note that shift length is in minutes, extend `form_text()` to do this nicely
engelsystem/engelsystem pull request #1336
Opened 2024-01-16 00:12 UTC by Lotterleben

As a user, when adding shifts, it wasn’t quite clear to me in which unit the shift length would be provided.

This PR clears this up by adding a little “in minutes” note under the text form. To make this note less obtrusive and create a visual information hierarchy, this PR also extends the `form_text()` function with a new `description()` parameter that lets us add such information as an optional [form text](https://getbootstrap.com/docs/5.3/forms/form-control/#form-text).

this is my first time writing PHP, so I hope what I did makes sense…

formatting note:
I’ve set up my editor to format according to PSR-12 on save, which messes with the existing indentation as you can see. However, `phpcs` does not seem to find a fault with this, so I’m not sure which is wrong – my editor settings or the pre-existing indentation

2024-01-16 00:15 UTC, Lotterleben commented on includes/pages/admin_free.php
> +                        form_text('search', __('form.search'), $search, null, false, null, null, null, ['col']),
this is a bit of a drive-by fix: when I checked all `form_text()` calls, I noticed that this call was missing an another argument in addition to the newly introduced one and that the last argument had a type mismatch. So I updated that on the go – the page looks fine in my browser, but that's the full extent of my testing. so, happy to reverse if desired.

2024-01-16 14:02 UTC, xuwhite requested changes
Thanks for your pull request 
I have some smallish request changes

2024-01-16 14:02 UTC, xuwhite commented on includes/pages/admin_shifts.php
> +                            null,
```suggestion
                            '',
```
should be the default value

2024-01-16 14:03 UTC, xuwhite commented
Overall I would prefer having the hint 'in minutes' in the title of the input field like 'Length (in minutes)'

2024-01-24 14:50 UTC, Lotterleben commented
> Overall I would prefer having the hint 'in minutes' in the title of the input field like 'Length (in minutes)'

Makes sense, I can also do that! Want me to also remove the change to `form_text()` to avoid unused code or keep it for future use?

2024-01-24 16:02 UTC, Lotterleben commented on includes/pages/admin_free.php
> +                        form_text('search', __('form.search'), $search, null, false, null, null, null, ['col']),
> 'col' is a class not a data-attribute please reverse that
ah, yup, I got the count wrong – what was missing is the last argument, i.e. `$data_attributes`. I've set this to `[]` now, hope that makes sense.

2024-01-27 15:59 UTC, xuwhite commented
Please remove it

2024-02-17 15:32 UTC, merged