driving license improvements
engelsystem/engelsystem pull request #1366
Opened 2024-03-14 18:06 UTC by xuwhite

2024-03-14 18:06 UTC, xuwhite commented
@MyIgel pls provide tests ;)

2024-03-16 16:36 UTC, MyIgel requested changes

2024-03-16 16:36 UTC, MyIgel commented on src/Controllers/Admin/UserSettingsController.php
> +            'has_car' => 'optional|checked',
That field is not changeable by admins and thus should not  be saved

2024-03-23 00:04 UTC, MyIgel requested changes
Just some smaller fixes / tweaks, then its ready to be merged :)

2024-03-23 00:04 UTC, MyIgel commented on src/Controllers/SettingsController.php
> +        if (!($this->checkDrivingLicense() || config('driving_license_enabled'))) {
```suggestion
        if (!config('driving_license_enabled') && !$this->checkDrivingLicense()) {
```

is cleaner in its intend (and checking the config before querying the db is also faster)

2024-03-23 00:04 UTC, MyIgel commented on src/Controllers/SettingsController.php
>          $user->license->has_car = (bool) $data['has_car'];
Imho that could be moved above the if but whatever

2024-03-23 22:47 UTC, MyIgel commented on src/Controllers/Admin/UserSettingsController.php
> +            !($this->auth->can('user.ifsg.edit')
the fix is not quite what i imagined (adding another indentation would be helpful) but yeah

2024-03-23 22:57 UTC, MyIgel requested changes

2024-03-23 22:57 UTC, MyIgel commented on src/Controllers/Admin/UserSettingsController.php
> +                    : ('user.ifsg.edit' || 'user.drive.edit'),
@xuwhite That does not work that way as its resolving to true and thus hides the menu point from shicos.

2024-03-23 22:57 UTC, MyIgel commented on src/Controllers/SettingsController.php
> +        if (!config('driving_license_enabled') && !$this->checkDrivingLicense()) {
That should be an `||` then

2024-03-23 23:55 UTC, MyIgel approved these changes
Looks good so far i guess :D

2024-03-24 13:34 UTC, merged