make Docker instructions for Development easier to discover and skim
engelsystem/engelsystem pull request #1412
Opened 2024-08-07 09:33 UTC by Lotterleben

I had a hard time figuring out what I did 8 months ago to get my Engelsystem dev system up & running. This PR attempts to make the necessary information easier to find and adds a "Troubleshooting" section that would've helped me and may just help someone else in the future.

2024-08-09 14:03 UTC, xuwhite requested changes
Thanks for the contribution. I have some small suggestions.

2024-08-11 15:47 UTC, Lotterleben commented on DEVELOPMENT.md
> +If unspecific issues appear try using Docker version >= 20.10.14.
This sentence is from your old docs, so I don't know which unspecific issues are referred to either 😅

2024-08-16 12:03 UTC, Lotterleben commented on DEVELOPMENT.md
> +make sure you're running your docker commends from `docker/dev`, not from `docker`
fixed manually

2024-08-16 12:04 UTC, Lotterleben commented
Addressed comments & squashed

2024-08-17 13:41 UTC, xuwhite commented on DEVELOPMENT.md
> +If unspecific issues appear try using Docker version >= 20.10.14.
True

2024-08-17 13:41 UTC, merged