add angel types metrics with membership state
engelsystem/engelsystem pull request #1434
Opened 2024-10-07 21:58 UTC by xuwhite

fixes #1432 

<img width="754" alt="Screenshot 2024-10-07 at 22 54 51" src="https://github.com/user-attachments/assets/248a3e28-3d2a-4a5c-a300-869ab7910331">

2024-11-03 15:21 UTC, MyIgel requested changes

2024-11-03 15:21 UTC, MyIgel commented on src/Controllers/Metrics/Stats.php
> +        $rawAngelTypes = AngelType::query()->select(['id', 'name', 'restricted'])->orderBy('id')->get();
```suggestion
        $rawAngelTypes = AngelType::query()->select(['id', 'name', 'restricted'])->orderBy('name')->get();
```

2024-11-03 15:21 UTC, MyIgel commented on src/Controllers/Metrics/Controller.php
> +                ], 'value' => $angelType['restricted'] ? ($angelType['members'] - $angelType['confirmed']) : 0,
this should eventually be calculated in the Stats class

2024-11-04 18:48 UTC, xuwhite commented
I'm merging for @MyIgel

2024-11-04 18:48 UTC, merged