Show goodie score on user goodie edit page
engelsystem/engelsystem pull request #1481
Opened 2024-12-25 14:11 UTC by MyIgel

Fixes  #1394

2025-01-02 13:44 UTC, xuwhite requested changes
very nice 
I have some minor change requests

2025-01-02 13:44 UTC, xuwhite commented on src/Helpers/Goodie.php
> +                    /** Is night shift */
this only doubles if it's a night shift, it doesn't multiply with the night shift multiplier

2025-01-02 13:44 UTC, xuwhite commented on src/Helpers/Goodie.php
> +                    /** Is night shift */
```suggestion
                    /* Is night shift */
```

2025-02-27 16:54 UTC, xuwhite requested changes
<img width="1305" alt="Screenshot 2025-02-27 at 17 52 30" src="https://github.com/user-attachments/assets/eac5ecc6-2d72-4d26-bca6-43fe6db064cd" />

the pre commit script fails please fix

2025-02-27 16:54 UTC, xuwhite commented on resources/lang/en_US/default.po
> +msgstr "T-Shirt score: %s"
```suggestion
msgstr "T-shirt score: %s"
```

2025-02-27 16:54 UTC, xuwhite commented on tests/Unit/Helpers/GoodieTest.php
> +class GoodieTest extends TestCase
please also write a test with night shifts and freeloads since you already had a issue in your calculations with this

2025-03-02 12:10 UTC, MyIgel commented
> <img alt="Screenshot 2025-02-27 at 17 52 30" width="1305" src="https://private-user-images.githubusercontent.com/73076134/417700672-eac5ecc6-2d72-4d26-bca6-43fe6db064cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA2NzYyODAsIm5iZiI6MTc0MDY3NTk4MCwicGF0aCI6Ii83MzA3NjEzNC80MTc3MDA2NzItZWFjNWVjYzYtMmQ3Mi00ZDI2LWJjYTYtNDNmZTZkYjA2NGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI3VDE3MDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMzI5N2FiYjRjOWQ1Yjk4ZmY3MDMxMzNmMjEwYjNiMmU2M2FmMGI0M2M5N2NjYjI2NTIyNDk5YTFhMDQyNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PKtx-ulYKY93WxO6WGUKdyrMhNCtkhMmQSumSV1lmoQ">
> 
> the pre commit script fails please fix

Looks like you have old dependencies installed, after running `composer install` this should be fixed :)

2025-03-02 12:10 UTC, MyIgel commented on tests/Unit/Helpers/GoodieTest.php
> +class GoodieTest extends TestCase
At the moment that code path is excluded as the query can't be run on sqlite

2025-03-24 21:22 UTC, MyIgel commented on tests/Unit/Helpers/GoodieTest.php
> +class GoodieTest extends TestCase
Its tested now as a feature test and thus not that stable but works ;)

2025-04-09 13:01 UTC, merged