[WiP] Bootstrap 5
engelsystem/engelsystem pull request #811
Opened 2021-04-29 20:00 UTC by weeman1337

Just as a preview; not finished yet.

Open:
* [ ] migrate rest of `/design`
* [ ] check all pages
* [ ] check all themes

#683

2021-04-29 20:07 UTC, MyIgel commented on config/config.default.php
> +            'navbar'        => 'dark',
I would have just searched for "dark" in the name, but that's also an option :D

2021-07-27 16:43 UTC, MyIgel commented
After the general markup changes are done we just need to fix the funny part of the design ;)

There are some small steps to do:

* check for theme variables that got removed / are not used anymore
* Resolve the `base.scss @todo`
* Fix the styling of all designs, especially on theme 7/35c3
  * button colors
  * headings color
  * forms bg

And all the other design glitches and quirks that ocured :upside_down_face:

2021-08-17 21:18 UTC, MyIgel commented
This PR is finally ready :heart_eyes: -> @msquare plz review ^^

As its already merged pushing it to the main branch should be enough ;)

2021-09-10 12:29 UTC, msquare requested changes
* Scrolling table headers in shift view have a transparent background
* Maintenance page css include is broken
* Login: Input-group-text background does not fit theme/high contrast

2021-09-11 08:55 UTC, weeman1337 commented on includes/sys_form.php
>      <div class="input-group date" id="' . $dom_id . '" data-min-date="' . $start_date . '" data-max-date="' . $end_date . '">
> Maintenance page css include is broken

✓

2021-09-11 08:56 UTC, weeman1337 commented
- [ ] Scrolling table headers in shift view have a transparent background
- [x] Maintenance page css include is broken
- [ ] Login: Input-group-text background does not fit theme/high contrast

2021-09-11 12:42 UTC, weeman1337 commented
* Date/time pickers added to the design page
* Date/time values from input are now taken over to the picker and vice versa

2021-09-11 14:16 UTC, merged

2021-09-11 14:17 UTC, msquare commented
Great work everybody! Thank you so much for upgrading Bootstrap and all the existing themes.