Database: Increase shift_size column size
engelsystem/engelsystem pull request #916
Opened 2022-05-23 21:45 UTC by xesxen

This resolves the following error message we're seeing:

```
 Exception: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'shirt_size' at row 1 (SQL: insert into `users_personal_data` (`first_name`, `last_name`, `pronoun`, `shirt_size`, `planned_arrival_date`, `user_id`) values (, , , 3XL-G, 2022-07-21 00:00:00, 101))
```

Users are running into this on signup, and since the user_personal_data is being saved before their `Angel` role has been assigned, these users are not able to do anything due to lack of rights.

2022-05-24 23:51 UTC, MyIgel commented
Thats a valid workaround, what values are you using for the shirt sizes?

2022-05-25 00:02 UTC, xesxen commented
Our current list consists of this: 
```php
[
        'S'    => 'Small Straight-Cut',
        'S-G'  => 'Small Fitted-Cut',
        'M'    => 'Medium Straight-Cut',
        'M-G'  => 'Medium Fitted-Cut',
        'L'    => 'Large Straight-Cut',
        'L-G'  => 'Large Fitted-Cut',
        'XL'   => 'XLarge Straight-Cut',
        'XL-G' => 'XLarge Fitted-Cut',
        '2XL-G' => '2XLarge Fitted-Cut',
        '3XL-G' => '3XLarge Fitted-Cut',
        '2XL'  => '2XLarge Straight-Cut',
        '3XL'  => '3XLarge Straight-Cut',
        '4XL'  => '4XLarge Straight-Cut',
        '5XL'  => '5XLarge Straight-Cut',
]
```

For this, an increase to varchar(5) would suffice, but an increase to 6 would make a bit more sense so someone is able to add an 2-character extension onto the type (eg. 5XL-GR for 5XL in GReen, or even 4XL-SG for "5XL Straight, color Grey)

2022-05-29 10:10 UTC, MyIgel requested changes
I found some changes that should be accommodated for ^^

(and also the commit message should be fixed too ;) )

2022-05-29 10:10 UTC, MyIgel commented on db/migrations/2022_05_23_000000_increase_tshift_field_width.php
> +        if (!$this->schema->hasTable('GroupPrivileges')) {
That check should be irrelevant as only a new table is  changed (and if used the later changed table should be referenced).

2022-05-29 10:10 UTC, MyIgel commented on db/migrations/2022_05_23_000000_increase_tshift_field_width.php
> +            'ALTER TABLE users_personal_data MODIFY shirt_size VARCHAR(6) ;'
To be portable, the creation of the statement should be done by the db abstraction and not manually as that forces it to be only MySQL compatible and breaks for SQLite which is used for tests.
A previous migration is for example [ChangeUsersContactDectFieldSize](https://github.com/engelsystem/engelsystem/blob/main/db/migrations/2018_12_21_000000_change_users_contact_dect_field_size.php#L43) which uses
```php
$table->string($column, $length)->change();
```

Also i think at least 10 would be eventually better here to have more room for others?

2022-05-29 10:10 UTC, MyIgel commented on db/migrations/2022_05_23_000000_increase_tshift_field_width.php
> +            'ALTER TABLE users_personal_data MODIFY shirt_size VARCHAR(4) ;'
Same here -> Direct SQL is not a great option

2022-05-29 10:10 UTC, MyIgel commented on db/migrations/2022_05_23_000000_increase_tshift_field_width.php
> +        if (!$this->schema->hasTable('GroupPrivileges')) {
Should not be needed

2022-06-02 09:55 UTC, MyIgel commented on db/migrations/2022_05_23_000000_increase_tshift_field_width.php
> +class IncreaseTshiftFieldWidth extends Migration
(sorry that i missed that last review)

2022-06-03 13:55 UTC, xesxen commented on db/migrations/2022_05_23_000000_increase_tshift_field_width.php
> +class IncreaseTshiftFieldWidth extends Migration
Whoops, I wonder how I didn't even spot the typo... fixed...

2022-06-03 14:03 UTC, merged

2022-06-03 14:04 UTC, MyIgel commented
Thx for your contribution!