Replace chart-js with backend rendering
engelsystem/engelsystem pull request #924
Opened 2022-06-09 20:39 UTC by weeman1337

@MyIgel :ping_pong: 

![chart5](https://user-images.githubusercontent.com/6216686/172939867-cf30590a-c49c-4763-b68a-87746de33c3d.png)

![chart10](https://user-images.githubusercontent.com/6216686/172939870-80a7185c-5dc1-4031-8db9-60063968c766.png)

![chart15](https://user-images.githubusercontent.com/6216686/172939871-c61ea6e0-9da6-410f-b83b-1b247f6cffa0.png)

![chart20](https://user-images.githubusercontent.com/6216686/172939877-d7272d23-db22-4735-bfa4-c0ee9634b42d.png)

![chart25](https://user-images.githubusercontent.com/6216686/172939882-dc5da882-a502-46fb-af9a-736bb0733ef8.png)

![chart30](https://user-images.githubusercontent.com/6216686/172939885-980f5607-f46a-429f-9a39-5cc212f7f8e6.png)

Ugly-mode :wink: 

![chart_uglymode](https://user-images.githubusercontent.com/6216686/172939888-18579f75-4c72-4f33-9389-398cf81c659c.png)

2022-06-12 16:38 UTC, MyIgel requested changes
I am not that convinced if introducing a new css naming convention (`.barchart__[...]`) which differs from the bootstrap names would be a great idea as it breaks consistency with bootstrap -> @marudor do you have an opinion on this?

It would also be nice to render a twig template for the charts :angel:

2022-06-12 16:38 UTC, MyIgel commented on includes/helper/graph_helper.php
> +        if ($date !== false) {
Imho that is redundant?

2022-06-12 16:44 UTC, weeman1337 commented on resources/assets/themes/bar-chart.scss
> +.barchar__graph-container {
:bearded_person: chart? :trollface:

2022-06-14 07:55 UTC, marudor commented
Honestly, as long as its ensured that CSS classNames do not clash its fine to have a different naming pattern.
Afterall it's mainly personal choice.

2022-06-18 21:43 UTC, weeman1337 commented
@MyIgel 

- CSS classes conform now to the Igel-style :trollface: 
- Less DOM nodes
- :x: `includes` → Twig + Helper class
- Print view works

2022-06-28 12:15 UTC, MyIgel requested changes

2022-06-28 12:15 UTC, MyIgel commented on src/Helpers/BarChart.php
> +class BarChart
I'm missing some tests for that class ;)

2022-06-28 12:15 UTC, MyIgel commented on resources/views/components/barchart.twig
> +        <div
Another space? 0o

2022-07-11 12:25 UTC, weeman1337 commented on src/Helpers/BarChart.php
> +        $step = $roundedMax / 5;
We can use stylelint :D

2022-07-11 12:26 UTC, weeman1337 commented on resources/assets/themes/theme0.scss
> +
We need stylelint :D

2022-07-11 21:30 UTC, merged